version: '3.9'
services:
  db:
    image: postgres:14
    restart: on-failure
    ports:
      - "5433:${POSTGRES_PORT:-5432}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}

  redis:
    image: redis
    restart: on-failure
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:${REDIS_PORT}"
    environment:
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
  
  back:
    image: back
    depends_on:
      - db
    restart: on-failure

    command: uvicorn main:app --host 0.0.0.0 --port ${BACK_PORT:-3001} --reload
    
    build:
      context: ./back/
      dockerfile: Dockerfile.dev
    ports:
      - "3001:${BACK_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-secret}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY:-secret2}
      
      STATIC_PATH: ${STATIC_PATH:-/static}

      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    volumes:
      - ./back/src/:/src


  worker_celery:
    image: back
    depends_on:
      - back
    command: celery -A celery_conf worker -l INFO -f /logs/celery_worker.log --concurrency 4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-secret}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY:-secret2}
      
      STATIC_PATH: ${STATIC_PATH:-/static}

      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}

  front:
    depends_on:
      - db
      - back
    build:
      context: ./front/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:${FRONT_PORT:-3000}"