name: CI
on:
    push: 
        branches: [ 'main' ]
jobs:
    build-and-push-images:
        runs-on: ubuntu-latest
        strategy: 
            fail-fast: false
            matrix:
                include:
                    - dockerfile: ./Dockerfile
                      context: ./back
                      image: andytakker/tth_back
                    - dockerfile: ./Dockerfile
                      context: ./front
                      image: andytakker/tth_front
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ matrix.image }}

            - name: Build and push Docker image stackoverfollowers
              uses: docker/build-push-action@v4
              with:
                file: ${{ matrix.dockerfile }}
                push: true
                context: ${{ matrix.context }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}

            
            
                  

            